spring.application.name=demo

# application.properties
spring.data.mongodb.uri=mongodb://localhost:27017/ecommerce
#spring.data.mongodb.uri=mongodb://admin:123@localhost:27017/ecommerce?authSource=admin
# Timeout de conexão (ms)
spring.data.mongodb.connection-timeout=5000
spring.data.mongodb.socket-timeout=3000

# Autenticação (se necessário)
#spring.data.mongodb.authentication-database=admin
#spring.data.mongodb.uri=mongodb+srv://admin:123@cluster0.abc123.mongodb.net/ecommerce?retryWrites=true&w=majority&authSource=admin

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# LocalStack S3 Config
aws.endpoint=http://localhost:4566
aws.access-key-id=teste
aws.secret-key=teste
aws.region=us-east-1
aws.s3.bucket-name=volume

# Desabilita validação de certificados SSL (opcional)
aws.s3.path-style-access=true